# if you update this file, please consider updating Vagrantfile too

language: cpp
os: linux
services:
  - docker
sudo: required

jobs:
  include:
    - name: "Qemu-based build"
      arch: amd64
      dist: bionic
      before_script:
        - docker run --rm --privileged sfalexrog/qemu-register:v4.1.0
      script:
        - docker run --rm -v $(pwd):/build sfalexrog/raspbian:buster-2019-09-30 /build/build.sh
    - name: "arm64 build"
      arch: arm64
      script:
        - docker run --rm -v $(pwd):/build sfalexrog/raspbian:buster-2019-09-30 /build/build.sh
